services:
  - type: web
    name: turnoya-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: turnoya-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://turnoya-cliente.onrender.com

  - type: web
    name: turnoya-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://turnoya-el1c.onrender.com/api

databases:
  - name: turnoya-db
    databaseName: turnoya
    user: admin
